### ISSUE TITLE
suckerberg and notifications

### ISSUE THREAD

**Issue by hfroese** [DeadSuperHero/hubzilla-themes#15]
First of all: good job.
I like suckberberg very much but there's one problem to me. 
Notifications aren't shown as proper as in redbasic because the group list is hiding it in most cases?

![index](https://user-images.githubusercontent.com/1968490/35690735-ef1f0520-0776-11e8-871a-d61f916789e9.png)

**Comment by DeadSuperHero** [comment]
Hey, thanks for catching this. Turns out the notifications widget has been missing from the Suckerberg PDL files, which are used for page layouts. For now, notifications are on the left-hand side of pages. That should make it more convenient for seeing notifications on mobile devices.

Fixed via 7e8a7d4 !

**Comment by hfroese** [comment]
Very nice but isn't it better placed **above menu** or **underneath forums**?

![index](https://user-images.githubusercontent.com/1968490/35696551-1915970c-0788-11e8-9e3f-bd2fe572d897.png)

**Comment by hfroese** [comment]
... and it is not pinned so new notifications are invisible whilst scrolling. Any way to change this?
